language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get install libboost-dev libboost-all-dev
  - sudo apt-add-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main"
  - sudo apt-get update
  - sudo apt-get install --force-yes clang-3.4 llvm-3.4
  - svn co http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
  - mkdir libcxx/build
  - cd libcxx/build
  - echo | g++ -Wp,-v -x c++ - -fsyntax-only
  - CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -G "Unix Makefiles" -DLIBCXX_CXX_ABI=libsupc++ -DLIBCXX_LIBSUPCXX_INCLUDE_PATHS="/usr/include/c++/4.6/;/usr/include/c++/4.6/x86_64-linux-gnu/;/usr/lib/gcc/x86_64-linux-gnu/4.6/include" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
  - make
  - sudo make install
before_script:
  - mkdir build
  - cd build
  - CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -DEXTRA_WARNINGS=Yes .. || cat CMakeFiles/CMakeError.log
script: make
#after_script:
#  - make test
