language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get install libboost-dev libboost-all-dev
before_script:
  - mkdir build
  - cd build
  - cmake -DEXTRA_WARNINGS=Yes ..
script: make
#after_script:
#  - make test
